# Generated by Django 4.2 on 2025-03-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('descripcio', models.CharField(max_length=50)),
                ('preu', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('nom_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.categoria')),
            ],
        ),
    ]
