# Generated by Django 5.2 on 2025-05-06 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('descripcio', models.CharField(max_length=50)),
                ('preu', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('nom_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.categoria', to_field='nom')),
            ],
        ),
    ]
