# Generated by Django 4.2 on 2025-03-31 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nom_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.categoria', to_field='nom'),
        ),
    ]
