# Generated by Django 5.2 on 2025-04-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0002_product_rating_alter_categoria_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
