version: '3.1'
services:
  db:
    image: postgres:13
    container_name: db_UF4
    environment:
      - POSTGRES_DB=pokeshop
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_UF3
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: paul@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: