# Generated by Django 4.2 on 2025-03-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cart', '0001_initial'),
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preu_total', models.IntegerField(max_length=50)),
                ('estat', models.CharField(max_length=50)),
                ('id_usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.user')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.product')),
            ],
        ),
    ]
