# Generated by Django 4.2 on 2025-03-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='preu_total',
            field=models.IntegerField(),
        ),
    ]
