# Generated by Django 5.2 on 2025-04-07 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_preu_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemorder',
            old_name='oder_id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id_usuari',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='itemorder',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
