# Generated by Django 4.2 on 2025-03-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymeny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tarjeta', models.CharField(max_length=16)),
                ('data_caducitat', models.DateField()),
                ('cvc', models.CharField(max_length=3)),
                ('estat_pagament', models.CharField(choices=[('pendent', 'Pendent'), ('completat', 'Completat'), ('fallit', 'Fallit')], default='Pendent', max_length=20)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
            ],
        ),
    ]
