# Generated by Django 4.2 on 2025-03-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Admin')], default='Pendent', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.carrito')),
                ('id_producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalog.product')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.user'),
        ),
    ]
