# Generated by Django 5.2 on 2025-04-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrito',
            old_name='id_carrito',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='itemcarrito',
            old_name='id_producte',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
