# Generated by Django 5.2 on 2025-04-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_rename_id_carrito_itemcarrito_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Admin')], default='Usuario', max_length=20),
        ),
    ]
